openapi: 3.0.0
info:
  title: Translate API v2
  description: The service does not operate with resources.
  version: v2
  x-y-docUri: api-ref
  x-y-baseUrl: https://translate.api.cloud.yandex.net
paths:
  /translate/v2/translate:
    post:
      tags:
      - Translation
      summary: Translates the text to the specified language.
      operationId: TranslationTranslate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TranslateRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TranslateResponse'
      x-y-navtitle: translate
  /translate/v2/detect:
    post:
      tags:
      - Translation
      summary: Detects the language of the text.
      operationId: TranslationDetectLanguage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DetectLanguageRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetectLanguageResponse'
      x-y-navtitle: detectLanguage
  /translate/v2/languages:
    post:
      tags:
      - Translation
      summary: Retrieves the list of supported languages.
      operationId: TranslationListLanguages
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListLanguagesRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListLanguagesResponse'
      x-y-navtitle: listLanguages
components:
  schemas:
    DetectLanguageRequest:
      type: object
      properties:
        text:
          description: |-
            Required.
            The text to detect the language for.

            The maximum string length in characters is 1000.
          type: string
        languageCodeHints:
          description: |-
            List of the most likely languages. These languages will be given preference when detecting the text language.
            Specified in [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) format (for example, `` ru ``).

            To get the list of supported languages, use a [listLanguages](/docs/translate/api-ref/Translation/listLanguages) request.

            The maximum number of elements is 10.
            The maximum string length in characters for each value is 3.
          type: array
          items:
            type: string
        folderId:
          description: |-
            ID of the folder to which you have access.
            Required for authorization with a user account (see [UserAccount](/docs/iam/api-ref/UserAccount#representation) resource).
            Don't specify this field if you make the request on behalf of a service account.

            The maximum string length in characters is 50.
          type: string
    DetectLanguageResponse:
      type: object
      properties:
        languageCode:
          description: |-
            The text language in [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) format (for example, `` ru ``).

            To get the language name, use a [listLanguages](/docs/translate/api-ref/Translation/listLanguages) request.
          type: string
    GlossaryData:
      type: object
      properties:
        glossaryPairs:
          description: |-
            Required.
            Array of text pairs.

            The maximum total length of all source texts is 10000 characters.
            The maximum total length of all translated texts is 10000 characters.

            The number of elements must be in the range 1-50.
          type: array
          items:
            $ref: '#/components/schemas/GlossaryPair'
    GlossaryPair:
      type: object
      properties:
        sourceText:
          description: |-
            Required.
            Text in the source language.
          type: string
        translatedText:
          description: |-
            Required.
            Text in the target language.
          type: string
        exact:
          type: boolean
          format: boolean
    Language:
      type: object
      properties:
        code:
          description: |-
            The language code.
            Specified in [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) format (for example, `` en ``).
          type: string
        name:
          description: The name of the language (for example, `` English ``).
          type: string
    ListLanguagesRequest:
      type: object
      properties:
        folderId:
          description: |-
            ID of the folder to which you have access.
            Required for authorization with a user account (see [UserAccount](/docs/iam/api-ref/UserAccount#representation) resource).
            Don't specify this field if you make the request on behalf of a service account.

            The maximum string length in characters is 50.
          type: string
    ListLanguagesResponse:
      type: object
      properties:
        languages:
          description: List of supported languages.
          type: array
          items:
            $ref: '#/components/schemas/Language'
    TranslateGlossaryConfig:
      type: object
      allOf:
      - title: glossary_source
        type: object
        maxProperties: 1
        properties:
          glossaryData:
            $ref: '#/components/schemas/GlossaryData'
            description: Pass glossary data in the request. Currently, only this way
              to pass glossary is supported.
    TranslateRequest:
      type: object
      properties:
        sourceLanguageCode:
          description: |-
            The text language to translate from.
            Specified in [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) format (for example, `` ru ``).

            Required for translating with glossary.

            The maximum string length in characters is 3.
          type: string
        targetLanguageCode:
          description: |-
            Required.
            The target language to translate the text.
            Specified in [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) format (for example, `` en ``).

            The maximum string length in characters is 3.
          type: string
        format:
          $ref: '#/components/schemas/TranslateRequestFormat_in_TranslateRequest_format'
        texts:
          description: |-
            Required.
            Array of the strings to translate.
            The maximum total length of all strings is 10000 characters.

            Must contain at least one element.
          type: array
          items:
            type: string
        folderId:
          description: |-
            ID of the folder to which you have access.
            Required for authorization with a user account (see [UserAccount](/docs/iam/api-ref/UserAccount#representation) resource).
            Don't specify this field if you make the request on behalf of a service account.

            The maximum string length in characters is 50.
          type: string
        model:
          description: |-
            Do not specify this field, custom models are not supported yet.

            The maximum string length in characters is 50.
          type: string
        glossaryConfig:
          $ref: '#/components/schemas/TranslateGlossaryConfig_in_TranslateRequest_glossaryConfig'
        speller:
          description: use speller
          type: boolean
          format: boolean
    TranslateRequestFormat:
      description: |2-
         - PLAIN_TEXT: Text without markup. Default value.
         - HTML: Text in the HTML format.
      type: string
      enum:
      - PLAIN_TEXT
      - HTML
    TranslateResponse:
      type: object
      properties:
        translations:
          description: Array of the translations.
          type: array
          items:
            $ref: '#/components/schemas/TranslatedText'
    TranslatedText:
      type: object
      properties:
        text:
          description: Translated text.
          type: string
        detectedLanguageCode:
          description: |-
            The language code of the source text.
            Specified in [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) format (for example, `` en ``).
          type: string
    TranslateRequestFormat_in_TranslateRequest_format:
      description: |-
        Format of the text.

         - PLAIN_TEXT: Text without markup. Default value.
         - HTML: Text in the HTML format.
      type: string
      enum:
      - PLAIN_TEXT
      - HTML
    TranslateGlossaryConfig_in_TranslateRequest_glossaryConfig:
      description: Glossary to be applied for the translation. For more information,
        see [Glossaries](/docs/translate/concepts/glossary).
      type: object
      allOf:
      - title: glossary_source
        type: object
        maxProperties: 1
        properties:
          glossaryData:
            $ref: '#/components/schemas/GlossaryData'
            description: Pass glossary data in the request. Currently, only this way
              to pass glossary is supported.
tags:
- name: Translation
  description: A set of methods for the Translate service.
