items:
  - name: Overview
    href: api-ref/index.md
  - name: Cluster
    items:
      - name: Overview
        href: api-ref/Cluster/index.md
      - name: create
        href: api-ref/Cluster/create.md
      - name: delete
        href: api-ref/Cluster/delete.md
      - name: get
        href: api-ref/Cluster/get.md
      - name: list
        href: api-ref/Cluster/list.md
      - name: listNodeGroups
        href: api-ref/Cluster/listNodeGroups.md
      - name: listNodes
        href: api-ref/Cluster/listNodes.md
      - name: listOperations
        href: api-ref/Cluster/listOperations.md
      - name: start
        href: api-ref/Cluster/start.md
      - name: stop
        href: api-ref/Cluster/stop.md
      - name: update
        href: api-ref/Cluster/update.md
  - name: NodeGroup
    items:
      - name: Overview
        href: api-ref/NodeGroup/index.md
      - name: create
        href: api-ref/NodeGroup/create.md
      - name: delete
        href: api-ref/NodeGroup/delete.md
      - name: get
        href: api-ref/NodeGroup/get.md
      - name: list
        href: api-ref/NodeGroup/list.md
      - name: listNodes
        href: api-ref/NodeGroup/listNodes.md
      - name: listOperations
        href: api-ref/NodeGroup/listOperations.md
      - name: update
        href: api-ref/NodeGroup/update.md
  - name: Version
    items:
      - name: Overview
        href: api-ref/Version/index.md
      - name: list
        href: api-ref/Version/list.md
